when:
  - event: [push, manual]

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      partial: false
      recursive: true
      tags: true

steps:
  - name: mirror to Github
    when:
      - event: [ push, manual ]
        branch: [ master, main ]
    depends_on: []
    image: codeberg.org/mathisdt/buildhelper:latest
    pull: true
    environment:
      TOKEN_GITHUB:
        from_secret: TOKEN_GITHUB
    commands: |
      git remote add github https://mathisdt:$TOKEN_GITHUB@github.com/mathisdt/$CI_REPO_NAME.git
      git push github
  - name: build
    when:
      - event: [ push, manual ]
    depends_on: []
    image: eclipse-temurin:25-jdk
    pull: true
    commands: |
      echo "installing packages..."
      apt-get update >/dev/null 2>&1
      apt-get -y install curl unzip wget >/dev/null 2>&1
      echo "done installing packages"
      echo "setting up Android SDK..."
      export ANDROID_SDK_ROOT="/sdk"
      export ANDROID_HOME="$ANDROID_SDK_ROOT"
      export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"
      # download URL from https://developer.android.com/studio?hl=en#command-line-tools-only:
      curl -s https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip -o /cmdline-tools.zip
      mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
      unzip -q /cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/
      mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
      rm -f /cmdline-tools.zip
      mkdir -p $ANDROID_SDK_ROOT/licenses
      echo "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
      echo "84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
      yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null
      # has to match the required version in app/build.gradle (platform AND build-tools):
      $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0" >/dev/null
      echo "done setting up Android SDK"
      TZ=Europe/Berlin ./gradlew clean test
      TZ=Europe/Berlin ./gradlew assemble
  - name: release on Codeberg
    when:
      - event: manual
        branch: [ master, main ]
    depends_on: [ build ]
    image: codeberg.org/mathisdt/releaseplugin:latest
    pull: true
    settings:
      TAG_PATTERN: "^v"
      RELEASE_NOTES: "see changelog: https://zephyrsoft.org/trackworktime/history"
      PATTERN_TO_RELEASE: 'app/build/outputs/apk/release/*.apk'
      TOKEN:
        from_secret: TOKEN_REPO_READWRITE
